### ISSUE TITLE
Decouple framework parts

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-core#103]
Attempts to split framework into truly independent parts get stuck in interdependencies problem.

Example: `yii\rbac\CheckAccessInterface`.
At the moment it is defined in `yiisoft/rbac` package.
This interface is used in `yii\web\User` class defined in `yiisoft/yii-web` package.
So `yii-web` package should require `rbac` which is unacceptable.
If we put `CheckAccessInterface` to `yii-web` then `rbac` should require `yii-web` which is unacceptable even more.
That's why PSR interoperability interfaces were introduced.
And I think this solution suits the problem too.

I propose to create package with Yii interoperability interfaces - `yiisoft/interfaces`.

Interfaces that have this interdependence problem are:

- `yii\rbac\CheckAccessInterface`
- `yii\view\ViewContextInterface`
- `yii\view\DynamicContentAwareInterface`
- `yii\di\FactoryInterface`
- to be continued

**Comment by samdark** [comment]
Agree.

**Comment by hiqsol** [comment]
Yes. Potentially it is a problem.
But in practice, mentioned interfaces are simple (1-3 methods) and were never changed (I've checked git history). If they've managed to stay for 2 major releases (2 and 3) I think they will do it up to 4.

Do you have better ideas?

**Comment by schmunk42** [comment]
What's about at least creating a separate package for each interface?

**Comment by samdark** [comment]
Yes, that may work better.

**Comment by kids-return** [comment]
`yii\view\ViewContextInterface` and `yii\view\DynamicContentAwareInterface` Should be placed in `view`.
Use `view` for require ,
For example `yii-web`

**Comment by viktorprogger** [comment]
I think `yii\web\User` should not implement `can` method (which is using `yii\rbac\CheckAccessInterface`). In my opinion this is not the `User` responsibility. We need to create an interface in `rbac` package (i.e. `Applicable`) with the `can` method and realize all the permission logic there. Current problem is not in interdependencies but in violation of SOLID principles (Single Responsibility and Interface Segregation at least).

**Comment by samdark** [comment]
@viktorprogger I agree about RBAC. Do you want to implement it in https://github.com/yiisoft/rbac?

**Comment by mozarcik** [comment]
I think that every such big change should be discussed more before implementing/changing it. I like those propositions but i wonder whether they are good enough to introduce another braking compatibility change.

When you introduce too many changes, adoption for new version will probably be low and it will be much harder to upgrade from yii2 to yii3.

**Comment by samdark** [comment]
@mozarcik it's 3.0. It is all about breaking changes.

**Comment by mozarcik** [comment]
First of all, I'm not against BC changes, because without it framework won't go forward. But if you make such big changes in every major release it is very hard to upgrade from one to another. I bet there are many yii1 applications out there because it is not trivial to upgrade to yii2. With many BC changes made in yii3 many devs won't upgrade to yii3 and will stay with yii2.

I think that every BC change should be discussed whether its best to introduce change without BC, just like proposed removing `can` method. It is easy to add new way of checking access with leaving this method and triggering deprecated warning. This way upgrade will be easier and it would allow to developers to change all `can` usages during deprecation period to new way. Then in maybe 3.1 such method could be removed entirely. 

Just my 2 cents.

**Comment by schmunk42** [comment]
Yii had a release cycle of 4 years for new major versions, that's outstanding compared to other frameworks.

> This way upgrade will be easier and it would allow to developers to change all can usages during deprecation period to new way. Then in maybe 3.1 such method could be removed entirely.

No, this makes it way harder, because too many users/devs won't care about deprecation warnings and there'd be complaints when 3.1 is released.

**Comment by rob006** [comment]
@mozarcik It would be better to create bridge package with web `User` class and this method. Removing method in `3.1` would be against semver.

But I agree with you about BC braking changes - new major release does not mean that we can break whatever we want. Yii 3 is not a new framework, there should be some sane upgrade path from Yii 2 to Yii 3.

**Comment by samdark** [comment]
More or less done by now. More packages are to be extracted if needed.
