### ISSUE TITLE
List of Yii 3.0 archtectural problems

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-core#104]
I want this issue to be a list of problems only with actual disscussions in their own issues.

- https://github.com/yiisoft/yii-core/issues/103 Decouple framework parts (packages interdependence)
- https://github.com/yiisoft/yii-core/issues/105 I18N global state.

The list is updated.

**Comment by samdark** [comment]
Discussions themselves are better to be conducted at official forum. We'll cross-link.

**Comment by samdark** [comment]
i18n thing was moved to i18n issues. Decoupling is mostly done.
