### ISSUE TITLE
Package from composer not exist- psr/log-implementation not exist

### ISSUE THREAD

**Issue by git579** [yiisoft/yii-core#112]
```
  Problem 1
    - yiisoft/yii-core 3.0.x-dev requires psr/log-implementation ^1.0 -> no matching package found.

```

**Comment by schmunk42** [comment]
You can use the implementations from Yii

```
        "yiisoft/log": "^3.0@dev",
        "yiisoft/cache": "^3.0@dev",
```

---

@yiisoft/reviewers Is there something about it in the docs? I also stumbled upon that.

**Comment by samdark** [comment]
@hiqsol ?

**Comment by hiqsol** [comment]
Yes, we need to have it documented: yii-core requires di, log and cache implementation, so yiisoft/log, di, and cache must be required if you require yiisoft/yii-core.

Also we can consider removing require di, log and cache implementations.
