### ISSUE TITLE
Missing yii3 docs reference in official website

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#117]
I see that Yii3 is not mentioned in any part of yii official website.

It would be useful that main docs/wiki links were listed here : https://www.yiiframework.com/wiki

adding a new tags called "yii3" that groups main articles such as:

https://www.yiiframework.com/wiki/2547/draft-understanding-yii-3
https://github.com/machour/yii3-kitchen-sink

Otherwise it is not simple to reach basical documents to yii3.

**Comment by machour** [comment]
There's a PR to add "Yii 3" to the Wiki versions: https://github.com/yiisoft-contrib/yiiframework.com/pull/416

Documentation for Yii 3 is far from ready, and is already a TODO item here: https://github.com/yiisoft/yii-core/blob/master/ROADMAP.md

**Comment by FabrizioCaldarelli** [comment]
Ok, but that PR has not beed merged, because I don't see in actual official website.

When will it be merged?

This could be an useful starting point to organize Yii3 documentation

**Comment by FabrizioCaldarelli** [comment]
How can I help to speed up publishing of yii3 docs?
