### ISSUE TITLE
Consider moving stuff that uses `ActiveRecord` to corresponding package

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-core#124]
E.g. `src/validators/ExistValidator.php` and `src/behaviors`.

**Comment by samdark** [comment]
Let's do it.

**Comment by machour** [comment]
Definitely a good idea, but this raises a little concern. As tests are more and more inter-connected with packages, a travis build per repository is not enough.

e.g, I could move those file to active-record, yii-core tests would pass, but I'd break most of db-xxx tests.

@hiqsol mentioned having a single travis instance running all tests from all packages (or something like that). Could it be setup ?

I'm trying hard to fix all travis setups, then all tests. This would help **a lot**.

**Comment by hiqsol** [comment]
> @hiqsol mentioned having a single travis instance running all tests from all packages (or something like that). Could it be setup ?

No, you understood me wrong. I don't have such idea :)
Tests are spread between packages and that's how it is going to stay.

> e.g, I could move those file to active-record, yii-core tests would pass, but I'd break most of db-xxx tests.

Why? No. We need to move it in a way that allows other tests to work.

**Comment by machour** [comment]
> No, you understood me wrong. I don't have such idea :)
> Tests are spread between packages and that's how it is going to stay.

My bad :) Yes, I'm all for each packages bundling their own tests, there's no questioning that.

What I really meant is: 
With Yii2 and a single repo, modifying the source code was safe, as all tests was ran by the test suite.

Now that packages are separated, a change in yii-core, validated by yii-core tests, could break other packages without us being aware of that.

It's only when tests are ran again for those packages (after a PR submission for example), that we would discover the breakage.

That's the problem I was referring to.

**Comment by hiqsol** [comment]
> Now that packages are separated, a change in yii-core, validated by yii-core tests, could break other packages without us being aware of that.

Very good point. Don't have a solution now.
I think periodic builds of all the packages will help.

Another consideration that every separate package have to be separated and covered with tests good enough for such breaks won't happen.

**Comment by terabytesoftw** [comment]
The idea of @machour  having a macro package to combine all the tests would be excellent, they could include the most only critical packages.

**Comment by samdark** [comment]
I don't like an idea of having tests that cover multiple packages at once. That would increase coupling of packages and that is what we're trying to avoid.

**Comment by SamMousa** [comment]
One thing we won't catch though is that a change in a dependency (like core) causes a break in another repo (like db).
One solution I've set up for Codeception is to have the core library run tests for yiisoft packages as well.
It makes it a bit slower but if we split it into several tasks it should be okay. 

So my suggestion would be that each PR on core would result on tests being run on core as well as pulling in yiisoft/db and running those tests.

**Comment by hiqsol** [comment]
> run the tests suite of B for changes to A as well.

Sounds reasonable. Is there a way to do it in Travis?

**Comment by SamMousa** [comment]
I scripted it manually.

https://github.com/Codeception/Codeception/blob/2.5/.travis.yml#L81

**Comment by FabrizioCaldarelli** [comment]
> I don't like an idea of having tests that cover multiple packages at once. That would increase coupling of packages and that is what we're trying to avoid.
> 
> Good coverage of individual packages should prevent integration breaks efficiently enough.

I'm agree with @samdark. Although initially I thought that trigger dependent packages travis build was a good idea, this would not solve the problem globally.

My approach is from a different point of view. 

What changes can generate breaks in depending packages? We can group them in:

1) Runtime errors;
2) Syntax errors, dued to changes in public and protected methods signature or properties names;

For the first, we have to write tests, as it has done so far.
For the second, we could generalize two tests for all packages: testAllMethodsSignatures and testAllPropertiesSignatures, in which we match (through reflection):

- all public and protected methods signature (function name, parameters and return type, if available);
- all public and protected properties (name and type, if available);

So we are sure that all depending packages that can access to public or protected methods/propriets will not have syntax errors  and nor runtime errors.

Even, we can test signatures for specific package version:

- testAllMethodsSignatures_1_0_0 : that contains all test for methods of v.1.0.0
- testAllMethodsSignatures_1_0_1 (@depends from testAllMethodsSignatures_1_0_0) : that contains only methods added after 1.0.0
- testAllMethodsSignatures_1_0_2 (@depends from testAllMethodsSignatures_1_0_1) : that contains only methods added after 1.0.1

but this is one more thing.

**Comment by rob006** [comment]
https://github.com/Roave/BackwardCompatibilityCheck

**Comment by SamMousa** [comment]
I like the proposed solution but still think we should run tests for our dependent libraries from the core library. Think of it as free extra integration tests.

**Comment by FabrizioCaldarelli** [comment]
> https://github.com/Roave/BackwardCompatibilityCheck

This is a very complete library. I think at something simpler, such as an array that contains method name, method parameters and return type (if available).

**Comment by samdark** [comment]
Mostly done by now.
