### ISSUE TITLE
yii\web\Linkable missing

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#125]
https://github.com/yiisoft/yii-core/blob/d87cecdb27b21773e75c08137fe644114823f8d8/src/data/Pagination.php#L13

What is the path in which put yii\web\Linkable php file?

**Comment by machour** [comment]
It's under the `yiisoft/yii-web` package: https://github.com/yiisoft/yii-web/blob/master/src/Linkable.php

**Comment by FabrizioCaldarelli** [comment]
This library is required also from db tests.

So Have we to add yiisoft/yii-web dependencies to yii/db-mysql ?

**Comment by FabrizioCaldarelli** [comment]
Thanks
