### ISSUE TITLE
Standard `tests/bootstrap.php`

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-core#128]
We have exactly identical `tests/bootstrap.php` in all the packages.
So we could create the standard one, put it into `yii-core` and require in other packages.
What do you think?

**Comment by hiqsol** [comment]
Not really in all the packages, but we could use the same `tests/bootstrap.php` and we should.

**Comment by samdark** [comment]
Good idea.

**Comment by machour** [comment]
You've read my mind :)

**Comment by hiqsol** [comment]
Used in `yii-captcha`
https://github.com/yiisoft/yii-captcha/commit/ae925afbd5dfcf23d181d9f03ce90fe7ca12b746

**Comment by machour** [comment]
Reopening so we remember to spread this change

**Comment by machour** [comment]
We also might want to document this.
https://github.com/yiisoft/yii-core/commit/5bb60b492228b5d826dac20afbf932047515768f#r31827488

**Comment by samdark** [comment]
I don't like it:

1. It's implicit.
2. There are extra dependencies.
3. Duplication eliminated is tiny.
