### ISSUE TITLE
Yii3 Dev organization

### ISSUE THREAD

**Issue by machour** [yiisoft/yii-core#129]
Hi there,

The team have been on vacations the past few days, and it was the perfect occasion for me to discover Yii3 state in peace (without big changes happening). That wasn't enough time to fully dive into all the changes, but enough to have a fair grasp, with the awesome help of @hiqsol 🙏 

I'd like to propose some ideas regarding how Yii 3 development is organized, because from my outside point of view, the current workflow (or lack of it) is one of the main blocking point if we want to get Yii 3 out.

Maybe something like this is already in use, and I've missed it, but if it doesn't, then I personally think it's a must.

### Tests
 
As you may have noticed, I've been working with @FabrizioCaldarelli on fixing travis setups, tests & various breakages in code. Figured out it will be a good way to get started and see what changed.

You can see the progress here: https://github.com/yiisoft/docs/blob/master/000-packages.md#yii-framework

I personally think that turning **and keeping** all Travis badges green should be the first focus of the Team as it gets back to working on Yii. 

#### Proposed solution:

Fix them all in a collective effort, then enforce the following rules:

 - Every PR merged in a repo, should have passed the travis build for that repo
 
 - If the PR introduce breakages in other packages, it should clearly mention it, along with instructions
 on how to fix them (if the author don't have the time to fix other packages).
 
We also need to come up with a way to trigger a travis build of all projects once in a while.

### Centralize Discussions

There are quiet a few important points being discussed for Yii3 development, sometimes on Slack, sometimes it's sparks on the 14th comment of a merged PR, .. The big picture have been split along with the packages, and that's not good project-wise.

#### Proposed solution:

Create a `yiisoft/rfcs` or `yiisoft/todo` repo and open an issue in it for every important decisions/discussion currently happening.

We would then either continue the dialog in the newly created issue, or just add a link to point at where the discussion is taking place.

Once concensus have been reached (when it's needed), the issue would be updated with the final decision, making it easier to know that there's a final word, and what that word is.

### Project Management

It's currently unclear who's working on what, and where the global situation at.

#### Proposed solution:

Set up GitHub Projects on the `rfcs` repo mentioned above, and use it to schedule some kind of roadmap for development.

Columns would go something like:

- `Discussing` : Decisions currently being discussed
- `Todo`: Decision have been made, awaiting PR
- `Ready` : Task completed & PR up for reviews / feedback
- `Spreading` : PR merged but other repos needs updates
- `Done` : The change have been made, and all other packages are adapted.
- `Postponed` : Discussed & approved, but to be implemented after 3.0.0

2019 looks like a promissing year for the framework!

**Comment by samdark** [comment]
1. Fully agree about tests.
2. Discussions for 1.0, 1.1 and 2.0 were happening at the forum. I can create a section there for RFCs.
3. I can create a board here at github (no need for it to be separate repo, boards are oragnization-wide) but I need someone to take care about it. I know how to do it but sometimes I have too little time to handle it.

**Comment by machour** [comment]
I'd be happy to help with 3 if you grant me proper access!

**Comment by samdark** [comment]
@machour invite sent.

**Comment by FabrizioCaldarelli** [comment]
Where will this board be accessible ?

**Comment by samdark** [comment]
https://github.com/orgs/yiisoft/projects/12

**Comment by schmunk42** [comment]
I saw that there's a channel #rfc on Slack, could we please avoid using that and use the forum instead. It's ridiculous that Slack charges you for you own content if you want to search in it later.

**Comment by FabrizioCaldarelli** [comment]
It's not active yet, right?

**Comment by samdark** [comment]
Closed slack channel.

**Comment by machour** [comment]
@samdark can the project visibility be set to public? It's currently org members only.

**Comment by samdark** [comment]
Done.

**Comment by jk2K** [comment]
maybe we can add [roadmap](https://github.com/yiisoft/yii-core/blob/master/ROADMAP.md) to the board, I don't know what can be done to speed up the release of yii3,
