### ISSUE TITLE
Access $this->app models.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-core#130]
### What steps will reproduce the problem?
$this->app (it is not available in the models).

### What is the expected result?
That is available and not using Yii: getApp () which is deprecated en Yii 3.0, remember that in Yii2, Yii::$app was available everywhere.

Of course you can go through the constructor $ this-> app to the model, but it would be cleaner if it were available by default, as in the controllers and views, and thus the use of the new commands is encouraged.

### Additional info
Commands in models for example:

```
$this->app->t
$this->app->user->login
$this->app->params
$this->app->security
```

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      |  7.1.23
| Operating system | Centos 7.0

**Comment by hiqsol** [comment]
A model should be your domain logic and should not interact with the framework at all.
So, my opinion - no. No application by default in `Model`.

**Comment by terabytesoftw** [comment]
Ok perfect, then it will be used Yii: getApp() that is deprecated in Yii 3.0 is as if it used Yii::$app, i understand your point of view, but then you should look for a better solution.

**Comment by machour** [comment]
@hiqsol how do you handle translations in this case?

In yii2, we used to use `Yii::t()` in `attributeLabels()`. What's the recommandation for Yii3 ?

**Comment by SilverFire** [comment]
> In yii2, we used to use `Yii::t()` in `attributeLabels()`. What's the recommandation for Yii3 ?

`Yii::t()` does not require application at all in Yii3

**Comment by terabytesoftw** [comment]
Not only is the translator used, people will use Yii :: getApp, when Yii was removed: $ app was to eliminate the static methods, that was at least what I understood.

**Comment by hiqsol** [comment]
@terabytesoftw 
There are always options. In general there are three:

- simple: use `Yii::getApp()` and in some cases it is just best solution
- DI: pass the application to the constructor: `public function __construct(Application $app)`
- look at the case and use not the application but what is necessary exactly, how SilverFire described before

**Comment by SilverFire** [comment]
> @SilverFire I agree that formatting shouldn't be part of the model, but sometimes it's just _handy_ to be able to do `<?= $model->formattedPrice ?>` (dynamic attr using formatter) in a view, instead of `<?= Yii::$app->formatter->myFunction($model->price) ?>`


Yes, it's handy, indeed. It's always hard to choose between _handy_ and _correct_, especially whey they act as antonyms :)

Last years I've heard a lot of critics that Yii allows too much _handy_ things that lead to awful consequences when they are abused, so we make some things not easy to do to discourage their usage.

In our projects, we prefer to make Widgets and Grids responsible for formatting. If it appears that model property should be formatted in a same manner in different places, we simply create a separate class for it.

**Comment by machour** [comment]
Thank you all for the valuables inputs. We'll definitely put all of that in the documentation @terabytesoftw.

**Comment by terabytesoftw** [comment]
After trying today, I agree with @silverfire and @hiqsol, it is not necessary for anything `$this->app` or `Yii ::getApp()`, the models are clean only with the logic.

It would be interesting to eliminate the use of `Yii::t` in the models, and look for a cleaner solution for the translation.

**Comment by pavel-redkin** [comment]
>> It would be interesting to eliminate the use of Yii::t in the models, and look for a cleaner solution for the translation.

What about Laravel-way ?
https://github.com/twisted1919/yii2-shortcut-functions/blob/master/src/functions.php

```
/**
 * Translation
 */
if (!function_exists('t')) {
    /**
     * @param string $category the message category.
     * @param string $message the message to be translated.
     * @param array $params the parameters that will be used to replace the corresponding placeholders in the message.
     * @param string $language the language code (e.g. `en-US`, `en`). If this is null, the current
     * [[\yii\base\Application::language|application language]] will be used.
     * @return string the translated message.
     */
    function t($category, $message, $params = [], $language = null) {
        return call_user_func_array(['\Yii', 't'], func_get_args());
    }
}
```

If ```t``` confuses then ```_t``` can be considered.
And it will be ```_t``` either ```__t``` to translate

Here is a relative discussion about "Global Helpers"
[https://github.com/yiisoft/yii2/issues/7352](url)

**Comment by samdark** [comment]
That is, essentially, similar kind of dependencies.

**Comment by pavel-redkin** [comment]
Yes. It is :)

---------------------------

Here's Laravel approach

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/helpers.php


```
if (! function_exists('app')) {
    /**
     * Get the available container instance.
     *
     * @param  string  $abstract
     * @param  array   $parameters
     * @return mixed|\Illuminate\Foundation\Application
     */
    function app($abstract = null, array $parameters = [])
    {
        if (is_null($abstract)) {
            return Container::getInstance();
        }
        return Container::getInstance()->make($abstract, $parameters);
    }
}


if (! function_exists('__')) {
    /**
     * Translate the given message.
     *
     * @param  string  $key
     * @param  array  $replace
     * @param  string  $locale
     * @return string|array|null
     */
    function __($key, $replace = [], $locale = null)
    {
        return app('translator')->getFromJson($key, $replace, $locale);
    }
}
```

Here's Yii approach

https://github.com/yiisoft/yii-core/blob/master/src/helpers/BaseYii.php
```
    public static function t($category, $message, $params = [], $language = null)
    {
        if (static::$container !== null) {
            return static::getApp()->t($category, $message, $params, $language);
        }
        return I18N::substitute($message, $params);
    }
```
-------------------------------------------------------------------

To make similar way for 
```
/**
 * Translation
 */
if (!function_exists('t')) {
    /**
     * @param string $category the message category.
     * @param string $message the message to be translated.
     * @param array $params the parameters that will be used to replace the corresponding placeholders in the message.
     * @param string $language the language code (e.g. `en-US`, `en`). If this is null, the current
     * [[\yii\base\Application::language|application language]] will be used.
     * @return string the translated message.
     */
    function t($category, $message, $params = [], $language = null) {
        return call_user_func_array(['\Yii', 't'], func_get_args());
    }
}
```


To adopt
```
        if (static::$container !== null) {
            return static::getApp()->t($category, $message, $params, $language);
        }
        return I18N::substitute($message, $params);
```
instead of
```
        return call_user_func_array(['\Yii', 't'], func_get_args());
```
in Global Helper



```Yii::t(```  would not be
Only ```Yii::getApp()``` would stay


----------------------------


Anyway ```_t``` can hide ```Yii::t(``` 
to prepare developers that ```Yii::t(``` will not exist

And only ```Yii::getApp()``` will stay in essential code base

**Comment by samdark** [comment]
The issue here is that all these are quite similar if we're looking strictly from dependencies perspective. We need to find a way that would allow us to de-couple from explicit usage of the application, helpers or helper-functions. If we won't fine a way that is both correct and convenient, we'll choose one of the less correct but handy ways doing so.

**Comment by terabytesoftw** [comment]
After trying and working on the truth the translations and the application are not necessary in the model, the translations must go in the views, in any case we can use the repository pattern and create classes that can be intermedaries between the controller and the model

**Comment by pavel-redkin** [comment]
> We need to find a way that would allow us to de-couple from explicit usage of the application, helpers or helper-functions

I got it :)

-----------------------------

> After trying and working on the truth the translations and the application are not necessary in the model, the translations must go in the views

Yes. It is.
I would not like to use ```Yii::t(``` in views.  
Free of framework coupling.
Simply ```t(``` would do the trick.
So that it would be easily to change framework.
To migrate from Yii 3 and to migrate to Yii 3


It looks like I am far from the issue discussion :)
Thank you guys. I will look for materials to consider the problem
