### ISSUE TITLE
Set model attributes passing values as array in constructor

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#131]
What about set model attributes passing values in constructor?

Should it be supported in Yii 3 ? Or should model configured parameter by parameter,

```
$m = new MyModel();
$m->attr1 = $value1;
$m->attr2 = $value2;
```

instead

`
$m = new MyModel([ 'attr1' => $value1, 'attr2' => $value2 ]);
`
https://github.com/yiisoft/db/blob/54e7a7ef9f7683bb641a13574c5c34cbd8c5dc61/tests/unit/validators/UniqueValidatorTest.php#L191

In this example, 'id' attribute is not set. We can still manage model configuration by passing values array, defining a construtor in BaseActiveRecord or even in Model class.

**Comment by samdark** [comment]
That's core thing since there are non-DB models.

**Comment by samdark** [comment]
The feature was both good and bad. Good because it was handy to use it with form submissions. Bad because it was way too easy to add another field to the model without defining proper validation for it and any form using that model was able to submit extra field value for it.

**Comment by samdark** [comment]
@hiqsol, @SilverFire what do you think?

**Comment by FabrizioCaldarelli** [comment]
But now it is not working passing array

`
$m = new MyModel([ 'attr1' => $value1, 'attr2' => $value2 ]);
`

$m->attr1 is null

Check this screenshot from 
vendor/bin/phpunit tests/unit/UniqueValidatorTest.php  --stop-on-failure --filter testValidateCompositeKeys

![schermata 2019-01-03 alle 00 53 52](https://user-images.githubusercontent.com/4108673/50618292-32e12080-0ef2-11e9-8b4f-31a3e1849dca.png)

My pointer is over $testV1

**Comment by samdark** [comment]
It is.

**Comment by FabrizioCaldarelli** [comment]
What is suggested syntax for Yii3 ?

`
$m = Yii::createObject(['__class' => MyModel::class, 'attr1' => $value1, 'attr2' => $value2]);
`
or 

```
$m = new MyModel();
$m->attr1 = $value1;
$m->attr2 = $value2;
```

**Comment by rob006** [comment]
We should just add `__construct()` with `$config` support to `yii\base\Model` and use `MyModel(['attr1' => $value1, 'attr2' => $value2])` as before.

**Comment by FabrizioCaldarelli** [comment]
Moving to constructor strict parameters configuration, I think that it will not be the way to do it.

**Comment by rob006** [comment]
Why? It is definitely better than using `Yii::createObject()` to instantiate model object with data :D

**Comment by FabrizioCaldarelli** [comment]
Read this thread: https://github.com/yiisoft/db/pull/44#discussion_r245469242

**Comment by rob006** [comment]
Something must have gone in the wrong direction if we need a factory to create a model from an array...

**Comment by samdark** [comment]
#136

**Comment by samdark** [comment]
How about the following?

```php
$post = Post::fromArray($data);
```

**Comment by FabrizioCaldarelli** [comment]
I suggest `::fromConfig` (even if little descriptive), so we could continue to pass old config parameters, that could contain also value for other fields, for example "scenario".

**Comment by samdark** [comment]
Yes. `fromConfig()` sounds better.
