### ISSUE TITLE
More strict type casting

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii-core#14]
Since this version will require php7.1 I think it should use a more strict typecasting on the class/interaces declarations.

For example at `yii\base\Controller::createAction()` the signature is

```php
public function createAction($id)
```

I think it would be better if its changed to

```php
public function createAction(string $id): ?Action
```

The same can apply to several other methods which might benefit from php7.1 typecasting.

**Comment by samdark** [comment]
Yes, could be done. Isn't a priority though.

**Comment by SamMousa** [comment]
As a side note, I think things like `createAction()` should throw exceptions not return `null`.

Currently this is the calling code:
```php
$action = $this->createAction($id);
if ($action === null) {
    throw new InvalidRouteException('Unable to resolve the request: ' . $this->getUniqueId() . '/' . $id);
}
```

**Comment by samdark** [comment]
@SamMousa it makes sense in many cases.

**Comment by cebe** [comment]
@SamMousa in that case it is about the type of exception. inside createAction() it would not be and "invalid route". createAction() may be used in other places where another type of error is needed.

**Comment by SamMousa** [comment]
Fair enough, it could be something like `InvalidArgumentException` since essentially the `$id` is not valid.

**Comment by SamMousa** [comment]
> Yes, could be done. Isn't a priority though.

@samdark note that changing return types / type hints, will be breaking BC, so if we don't do it upon release of Yii 3 we might be stuck with it for a long time...
All extending classes need to update their function signatures, so it might make sense to prioritize this if we want to do it for 3.

**Comment by marcelodeandrade** [comment]
Refactoring the core with> = 7.0 version without PHP latest features, It's a nonsenseless. Yeah! It's a huge change.

Can not be a high priority in this moment, but i believe it's should be done.

**Comment by cebe** [comment]
Adding strict typing does not work in many places where we allow different input, so we need a concept for where it should be added and where not.

**Comment by SamMousa** [comment]
Well, in cases where there's a single type it can and should be done IMO.
In cases where there's a mixed type we can leave it as is, or consider refactoring to make it a single type.

**Comment by samdark** [comment]
It's applied here and there but generally we're doing it.
