### ISSUE TITLE
Code coverage fails with PHP 7.3

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-core#141]
All tests now pass for the core package but overall build fails because of code coverage with PHP 7.3:

https://travis-ci.org/yiisoft/yii-core/jobs/475954006

```
The command "phpdbg -qrr vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --exclude-group wincache,xcache" exited with 1.
```

**Comment by machour** [comment]
Nice work!

The relevant Travis error seems to be "Error:         Incorrect whitelist config, no code coverage will be generated."

If this is complicated to fix ATM, I suggest disabiling it for now. We need to have a green build status asap for next changes.
