### ISSUE TITLE
`data` dirs in tests 

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-core#144]
At the moment there are several `data` dirs in tests (it's a bit confusing):
- tests/data
- tests/framework/validators/data
- tests/framework/test/data

Also there is `tests/framework/data` but it corresponds to tests for `src/data`.

Couldn't we collect them together like this:
- tests/data/
- tests/data/validators
- tests/data/test

And in other packages move `data` too.
For we had standard place for data for tests `tests/data`.

**Comment by samdark** [comment]
Either that or we can dtore data close to the code.

**Comment by machour** [comment]
`tests/data` sounds like a good place.

**Comment by rob006** [comment]
I prefer to keep test data closer to tests classes - it is easier to navigate and refactor if files required for specific test are in one place.

**Comment by hiqsol** [comment]
Ok, it could be close to test classes but not partially here and partially there. As it is at the moment.
We could have some `getDataPath($arg)` in tests as soon as we put all data in standard place.

**Comment by samdark** [comment]
Not a problem anymore since most packages are now separate. If you still notice problems, please report to package issues.
