### ISSUE TITLE
Debug code in Model?

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii-core#148]
Was just looking at the [`Model`](https://github.com/yiisoft/yii-core/blob/master/src/base/Model.php) class and think some debug code has crept in.

https://github.com/yiisoft/yii-core/blob/master/src/base/Model.php#L184

**Comment by samdark** [comment]
@hiqsol your stuff. Could be removed, right?

**Comment by schmunk42** [comment]
I don't know about the use-case, but sometimes it is helpful to have `Yii::error()` in such cases, even if they are very rare.

**Comment by hiqsol** [comment]
Sorry, my bad. Removed.
