### ISSUE TITLE
Middleware support in 3.0

### ISSUE THREAD

**Issue by vstokarev** [yiisoft/yii-core#15]
Previously there was a pull request related to middleware support: https://github.com/yiisoft/yii2/pull/15416. 
I don't see it in the change log now: https://github.com/yiisoft/yii-core/blob/master/CHANGELOG.md

Did you remove it or just forgot to add to the change log?

And also one more question: where can one find info about 3.0 current status, plans and discussions?

**Comment by hiqsol** [comment]
That PR is indeed merged in `yii-web`. Changelog files could be inconsistent with changes.

Middlewares will be supported in 3.0.
And there is discussion inside yii-team to rewrite some core functionality with middlewares. We'll see.

Concerning last question.

Here you can find description of ongoing changes in 3.0: https://github.com/yiisoft/yii-core/blob/master/UPGRADE.md

Unfortunately there is no current status page. Current status approximately is:

- massive split and renaming seems to be finished
- most of big changes listed in UPGRADE are done
- still some changes are in progress
- few changes (including middleware) are in internal Yii-team discussion and evaluation
- [application template](https://github.com/yiisoft/yii-project-template) is mostly working
- tests that are now spread across all packages are to be fixed
- ROADMAP page needs to be updated

To catch ongoing discussions you can watch Yii 3.0 repositories you are interested in (at least `yii-core`, `yii-base-web` and `yii-project-template`) on GitHub.
