### ISSUE TITLE
\yii\base\Application constructor parameter

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#152]
In constructor parameters doc, the first parameters should be an array, instead in __construct definitions has to implement ContainerInterface interface.

Should the constructor comment updated to

`@param ContainerInterface $object that must contain both [[id]] and [[basePath]]. 
`

?

https://github.com/yiisoft/yii-core/blob/dedf7d9aca109ea777747287de920e423f8d1a46/src/base/Application.php#L179-L192

**Comment by samdark** [comment]
Yes.
