### ISSUE TITLE
我认为yii3最应该解决的就是composer包过大的问题

### ISSUE THREAD

**Issue by gudufy** [yiisoft/yii-core#154]
composer基本就是把git里的所有代码都下到本地了，有些代码根本就用不到，一个项目下来composer目录都有几十甚至上百兆，应该借鉴.net项目只引用dll，也就是我用到的文件，不用的文件就处理掉

**Comment by razonyang** [comment]
1. vendor 目录大小由项目所依赖的库决定的，这些是不可或缺的。
2. 相对于 yii2, yii3 已经将 yii2 独立成多个单独的包，以减少依赖，如：core、web、console、rest、rbac、di、db 等等。
3. 生产环境可以通过 Composer 参数`--no-dev` 参数不安装开发包。
4. 另外，即使 vendor 上百兆并不会影响什么，硬盘是廉价的。

**Comment by machour** [comment]
This is how composer works.
