### ISSUE TITLE
Should not require yii-web

### ISSUE THREAD

**Issue by machour** [yiisoft/yii-core#155]
Currently, `src/data/` files require yii-web:
  https://github.com/yiisoft/yii-core/blob/master/src/data/Pagination.php#L12

**Comment by Alex-Bond** [comment]
Actually its a good question why Pagination is in core package)

**Comment by machour** [comment]
I guess it's still here because Pagination could be used either from Web, or API, or even CLI for that matter.
Putting it into `yiisoft/yii-dataview`could make sense for the "web" part, but not the others.. 🤔

**Comment by Alex-Bond** [comment]
@machour i think we gonna have to change it to an abstract class and remove Yii-web dep and made something like Application class.
I found another thing that I'm working on - it uses request object, but logically it must be available only of Yii-web, not CLI.

**Comment by samdark** [comment]
API is web.

**Comment by samdark** [comment]
To me it makes sense.

**Comment by samdark** [comment]
@hiqsol what do you think?

**Comment by hiqsol** [comment]
As for me, there are still things in core that should be moved out :)

**Comment by machour** [comment]
@Alex-Bond would you like to take care of this?

**Comment by Alex-Bond** [comment]
@machour at this moment I have PSR-15 and Error processing in my backlog in order to at least partially support RoadRunner.
If no one will take care of it before I finish with other things I can look into it.

**Comment by pavel-redkin** [comment]
Hi !
> Currently, src/data/ files require yii-web:
> Putting it into yiisoft/yii-dataview

Is it about ?
1) to move
https://github.com/yiisoft/yii-core/tree/master/src/data/*.php
into 
https://github.com/yiisoft/yii-dataview/tree/MOVED_YII_WEB_WIDGETS/src
(MOVED_YII_WEB_WIDGETS - branch name)

2) to remove php files and 'data' folder
https://github.com/yiisoft/yii-core/tree/MOVED_YII_WEB_WIDGETS/src/data/*.php


master -> MOVED_YII_WEB_WIDGETS

**Comment by samdark** [comment]
Done by now. data and data-widgets are extracted into separate packages.
