### ISSUE TITLE
Url::ensureScheme should fail hard for non absolute paths

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#178]
A function called `ensureXYZ` should not fail silently.

Calling `Url::ensureScheme($url, 'https')` should never return a string that does not start with 'https://'.
Instead, ensureScheme should throw an exception if it cannot ensure the scheme.

**Comment by samdark** [comment]
Agree.

**Comment by samdark** [comment]
There's no Url class anymore since we're dealing with PSR-7.
