### ISSUE TITLE
What is the current dependency between repo?

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-core#183]
Is it possible to clarify the dependencies between repos to prevent meaningless PR?

**Comment by schmunk42** [comment]
Do you have an example of meaningless PRs?

See also about deps: https://github.com/yiisoft/docs/blob/master/000-packages.md

**Comment by machour** [comment]
@samdark could you share your dependencies schema?

**Comment by machour** [comment]
@kids-return Updated the **current** dependencies graph between repositories: https://yii3.idk.tn/site/packages
There's a lot of unwanted dependencies to fix.

**Comment by schmunk42** [comment]
@machour Nice!

I just remembered this one https://github.com/clue/graph-composer

**Comment by schmunk42** [comment]
Why are the `db-` packages so loosely connected? Eg. not all depend on `db`

**Comment by kids-return** [comment]
E.g.
According to the previous discussion, `yii-base-api` needs to rely on `yii-web`
current
```
yii-base-api -> yii-rest -> yii-core
```
What should be the right thing?
```
yii-base-api -> yii-rest -> yii-web -> yii-core
or
yii-base-api -> yii-web -> yii-rest  -> yii-core
```
I found a lot of similar problems. And I am not sure which warehouse to go to repair.
I think Core Team can sort out the right and correct dependencies to make it easier for other developers to improve.

**Comment by kids-return** [comment]
E.g.
`yii-core` current dependency `rbac`.
Is Core Team ultimately going to `yii-core` dependency `rbac`

**Comment by kids-return** [comment]
It would be great if you planned it in the early stage.
Maybe we can define a `dependency.md` and update him according to the discussion.
This will be very clear how to do it, and it will be more convenient for people to participate.

**Comment by samdark** [comment]
https://forum.yiiframework.com/t/revised-package-dependencies/125359/3 this schema?

**Comment by kids-return** [comment]
```
├── yii-base-api
│   └── yii-rest
│       └── yii-web
│           ├── view
│           └── yii-core
│               ├── cache
│               ├── di
│               ├── event-dispatcher
│               └── log
```
```
├── yii-base-web
```
```
├── yii-base-cli
```
How to make something like this
Start with `yii-base-web` `yii-base-api` `yii-base-cli ` respectively.
Only consider the dependencies between `yiisoft` `repo` 
Create a `dependencies.md` file and update this file the first time if a change occurs.

**Comment by My6UoT9** [comment]
My 2 cents, there are multiple levels of inheritance. In my opinion there should be no more then 3. Else the human brain gets a hard time to grasp it.
While OO is great, functional programming is also great. The 2 worlds have to be combined, going full on OO is a pitfall. Maybe reconsider, and read up about problems with OO.
In my opinion there is to much hype around OO, OO is great when used correctly though.

https://en.wikipedia.org/wiki/Object-oriented_programming#Criticism

**Comment by machour** [comment]
@My6UoT9 this is kind of agreed on, but out of topic. The graph laid out by @kids-return is not about objects inheritance but packages dependencies.

**Comment by kids-return** [comment]
If this works, I will try to build `dependencies.md` with my understanding.

**Comment by samdark** [comment]
You can't draw it with a tree since it is, in fact, a graph. https://yii3.idk.tn/site/packages is a good start. Then https://en.wikipedia.org/wiki/Package_principles could be applied to split these further and eliminate unwanted dependencies. See what I'm doing with i18n: https://github.com/yiisoft/i18n

**Comment by arslan-butt** [comment]
@samdark  Please update the the link under Libraries ->  

> yiisoft/rbac

 to (https://github.com/yiisoft/rbac) currently its going on https://github.com/yiisoft/log

**Comment by machour** [comment]
@arslan-butt where do you see the problem?

**Comment by arslan-butt** [comment]
In the New composer packages (https://yii3.idk.tn/site/packages)
![image](https://user-images.githubusercontent.com/24808064/56076409-18202100-5dea-11e9-9f26-9f67cb1b7d97.png)

**Comment by machour** [comment]
@arslan-butt thank you, fixed it (for next times, open an issue at https://github.com/machour/yii3-kitchen-sink please)

**Comment by machour** [comment]
@kids-return @schmunk42 this might interest you: https://yii3.idk.tn/data-view/list-view

It's the `dependencies` of each packages, excluding `dev`. Let me know if you have other visualizations in mind

**Comment by schmunk42** [comment]
@machour This is pretty cool and much better than showing all packages together.
