### ISSUE TITLE
Yii3 assets path not correctly reference if installed in subfolder

### ISSUE THREAD

**Issue by chief725** [yiisoft/yii-core#184]
### What steps will reproduce the problem?
install yii3 in a subfolder of an server
### What is the expected result?
css and js file paths should include subfolder path.
### What do you get instead?
css and js file paths not include subfolder path. reulut in css files not found.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.?
| PHP version      | 7.2 
| Operating system | window 10

![捕获](https://user-images.githubusercontent.com/1095122/55635706-f4f6df80-57f3-11e9-98d5-8f436405eeb9.PNG)

**Comment by schmunk42** [comment]
Should be moved to https://github.com/yiisoft/yii-web

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/issues/56
