### ISSUE TITLE
cannot use @web or @webroot in config.

### ISSUE THREAD

**Issue by jpodpro** [yiisoft/yii-core#186]
i want to setup some aliases in the app config such as an uploads directory:
'aliases' => [
        '@uploadsurl' => '@web/uploads'
    ],

however this fails because @web is unavailable in the config stage which sucks. @web and @webroot shouldn't need to wait until Request to be defined. are they not extremely independent values?

**Comment by samdark** [comment]
Closing since implementation is too different now.
