### ISSUE TITLE
Deal with relative links in Formatter::asUrl()

### ISSUE THREAD

**Issue by alexantr** [yiisoft/yii-core#192]
When using relative links (or links w/o http protocol) with `Formatter::asUrl()` they become broken:
`/some/page.html` -> `<a href="http:///some/page.html">/some/page.html</a>`
`#anch123` -> `<a href="http://#anch123">#anch123</a>`
`//example.com/page/` -> `<a href="http:////example.com/page/">//example.com/page/</a>`

Is a good idea to add some checks in method `asUrl()`? Like this:
```php
if (strpos($url, '://') === false) {
    if (strpos($url, '/') !== 0 && strpos($url, '//') !== 0 && strpos($url, '#') !== 0) {
        $url = 'http://' . $url;
    }
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      | all
| Operating system | all

**Comment by samdark** [comment]
There's no URL formatter now so nothing to apply issue to.
