### ISSUE TITLE
Nested model attribute label issue

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii-core#193]
### What steps will reproduce the problem?

Define a class with nested models:

```php
class CompletedOrderReviewForm extends Model {
   /** @var OrderReview */
   public $summaryReview;

   /** @var OrderReview */
   public $primaryReview;

   /** @var OrderReview[] */
   public $otherReviews = [];

	public function rules() {
		return [
			[['summaryReview', 'primaryReview', 'secondaryReviews'], 'safe'],
                        // some complex validation here
		];
	}
}
```
Render inputs through ActiveForm:

```php
<?= $form->field($formModel, 'summaryReview[rate]')
		->textInput([
			'type' => 'number'
		]) ?>
```

### What is the expected result?

The expected label of the input is 'Rate'.

### What do you get instead?

The label of this input is 'Summary Review'.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.4
| Operating system | Windows 8.1 64 bit

**Comment by samdark** [comment]
There are no models anymore.
