### ISSUE TITLE
Remove wigets and grid

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii-core#2]
It's necessary remove widgets and grid from core.

I think better to create a new repository `widgets` and move the source

**Comment by hiqsol** [comment]
Thank you for important question.
We're considering and discussing what to leave and what to move.
But didn't yet think to remove widgets and grid.
Why do you think it is really necessary?

**Comment by hiqsol** [comment]
Roadmap for planned changes will be available later, after we do necessary experiments.

**Comment by leandrogehlen** [comment]
>Why do you think it is really necessary?

Because, this is a view part, and in some cases (like rest applications), these sources is not necessary.

**Comment by cebe** [comment]
we are experimenting with splitting framework into multiple repos:

- core
- web
- console
- ...

so this is exactly what is happening here :)

**Comment by hiqsol** [comment]
Yes, I'm ok to go deeper and split more parts :)

**Comment by leandrogehlen** [comment]
@cebe, yes, and i think a excellent choice, but the directories `grid` and `widgets` were kept,
in `core` repository.

**Comment by cebe** [comment]
this is not final in any way, we are currently evalulating and playing aroung with this idea.

**Comment by machour** [comment]
Can be closed as things were moved to `yiisoft/yii-dataview`.
