### ISSUE TITLE
Change namespace to Yiisoft\Core?

### ISSUE THREAD

**Issue by schmasterz** [yiisoft/yii-core#201]
According to  composer.json this package doesn't require yii-something. May be it is not a bad idea to rename it to yiisoft/core and change namespace to Yiisoft\Core?
Just a suggestion. 
See https://github.com/yiisoft/yii-web/pull/76

**Comment by samdark** [comment]
I doubt the package would survive in the end. Let's leave this issue open for now.

**Comment by terabytesoftw** [comment]
The core will not disappear only now it is divided into functional packages which I think is much better, in the end the Core package will be the one that allows to join the necessary packages for the YiiFrameWork to work.

Core Package: (Core, Di, Factory, Event Dispatcher, View, Web, Logger, Cache, Console) for example.

As a suggestion, it would be nice to rename yii-core to core, yii-web to web, yii-console to console, the packages that were divided from the core, their namespace is Yiisoft/Package, and those that add functionality as extensions Yiisoft/Yii/Package, I know that this was discussed a lot but as it develops things change.

**Comment by samdark** [comment]
Nope, that won't be called "core". That would be `yii-web` for all things web, `yii-console` for all things console and application templates to rule them all.

**Comment by samdark** [comment]
But overall, I'm fine with renaming namespace now. Won't take much effort.

**Comment by terabytesoftw** [comment]
You could place the packages with your namespace, so that when the developers make contributions have the namespace correctly, I think the forum would be a good place for it, as well as that you are using PSR-2 for the style guide under https://docs.styleci.io/presets#psr2

**Comment by samdark** [comment]
It's not Yiisoft/Core btw. but Yiisoft/Yii/Core.

**Comment by machour** [comment]
> I doubt the package would survive in the end.

I'm also unsure this package will survive, and having an old-form namespace is clearer for me. (when I see a `use yii\blabla` in a package, I immediately know we have an unchecked piece of code)

Let's leave it as is for now.

**Comment by samdark** [comment]
Won't be done since the goal is to get rid of core package.
