### ISSUE TITLE
When will yii3 be released? 

### ISSUE THREAD

**Issue by godla** [yiisoft/yii-core#202]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by schmunk42** [comment]
"When it is done" ;) https://forum.yiiframework.com/t/yii-3-0-when-will-it-be-released/123633

Related: https://github.com/yiisoft/docs/blob/master/003-roadmap.md
