### ISSUE TITLE
Repo merges into a repo and then splits

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-core#208]
E.g.
https://github.com/symfony/symfony/tree/4.4/src/Symfony
https://github.com/laravel/framework/tree/5.8/src/Illuminate
https://github.com/hyperf-cloud/hyperf/tree/master/src

split
https://github.com/laravel/framework/tree/5.8/bin
https://github.com/hyperf-cloud/hyperf/tree/master/bin

This looks more intuitive。
Avoid some unnecessary dot files
It's also easier to fix
Development time ide does not need to load a lot of repo
and many more
How is this approach?

**Comment by schmunk42** [comment]
It's super annoying, because you can not create PRs to the splitted repos from your `vendor`.
If you wanna do that and install the "monorepo" you can't have different versions of the splitted ones.

**Comment by samdark** [comment]
I don't think we're going back to monorepo + split approach.
