### ISSUE TITLE
Yii Core LTS

### ISSUE THREAD

**Issue by tomlutzenberger** [yiisoft/yii-core#22]
The [ROADMAP.md](https://github.com/yiisoft/yii-core/blob/master/ROADMAP.md) says that LTS will be announced for v4.0 in 2018.
Are there already some details around? I'm working with Yii2 for over a year now and tried to convince my co-developers to use it for new projects. To avoid risks and future problems (like AngularJS / Angular had) some sort of LTS would be essential. Can you provide some infos at this point?

**Comment by ddziaduch** [comment]
We are still using Yii1 in our main project ;)

**Comment by tomlutzenberger** [comment]
@samdark Besides code contributions, is there something one could do to speed things up? I'd really like to give the Yii team a helping hand (code, docs, ... you name it) 😃

**Comment by cebe** [comment]
> We are still using Yii1 in our main project ;)

exactly, Yii LTS is typically quite long compared to "LTS" versions of other projects which are not really made for long term...

**Comment by samdark** [comment]
@tomlutzenberger sure. Managing 2.0 extensions releases: testing, moving issues that could be solved later to next releases, writing announcements.

**Comment by tomlutzenberger** [comment]
Sounds interesting. We should talk about this in detail.

**Comment by zz** [comment]
need a foundation

**Comment by cebe** [comment]
> need a foundation

we are working on that.
