### ISSUE TITLE
An internal server error occurred.

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii-core#24]
| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      |  7.1.17
| Operating system | Centos 7

Your Commit https://github.com/yiisoft/yii-core/commit/3e3a97879ef846fabe75a9f18633f9ab4a72aeaa, generates this error,

Thks,

**Comment by hiqsol** [comment]
There was a typo in `Yii::getAlias()`.
Should fix the problem (but I don't know exactly, you've given not enough info).

**Comment by terabytesoftw** [comment]
Work Fine, 

Thks,
