### ISSUE TITLE
Remove \Yii::$app->requested*

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#47]
Currently there's 3 properties in `yii\base\Application` that seem to have no function than for debugging:
```php
	/**
	 * @var string the requested route
	 */
	public $requestedRoute;
	/**
	 * @var Action the requested Action. If null, it means the request cannot be resolved into an action.
	 */
	public $requestedAction;
	/**
	 * @var array the parameters supplied to the requested action.
	 */
	public $requestedParams;
```

The commit message where they were added was `Yii debugger WIP`. I think it makes sense to remove these.

Instead the debug module should use events to gather the data it needs and they should not be stored as public properties on the application class.

**Comment by GHopperMSK** [comment]
https://github.com/yiisoft/yii-web/blob/2b3d8e9354febe8e2588d1ea3205dc28666dfd2d/src/User.php#L448-L450

Isn't it related? How can we replace `app->requestedRoute` statement?
