### ISSUE TITLE
Dont modify behaviour specifically for tests

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii-core#49]
The framework code should never use specific behaviour like this:

```php
if (YII_ENV_TEST) {
   throw new ExitException($status);
}

```
https://github.com/yiisoft/yii-core/blame/aa1c38c3e0533c4def419ecdaf53d6a5f8167514/src/base/Application.php#L678

It is responsibility of unit test to decide whether returned response code is expected or not.

**Comment by hiqsol** [comment]
Agree.
But it's very old code from 2014.

https://github.com/yiisoft/yii-core/blame/680b1d4400b43510a39dc6923fb80e2d953ccf7c/src/base/Application.php#L697

I don't know if it can be removed.
Maybe @samdark or @cebe will help.

**Comment by samdark** [comment]
Agree. Will look into why it's used in the first place...

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/issues/15202

**Comment by samdark** [comment]
I think we can do it differently so no explicit `exit()` is needed except in the `index.php`.

**Comment by xicond** [comment]
btw, where's the basic Exception => like ExitException

**Comment by samdark** [comment]
@xicond there is none. For web you can set response code to response object directly. For console just `return <code>` does the job.

**Comment by samdark** [comment]
We aren't doing that anymore.
