### ISSUE TITLE
Add `Jsonable` interface

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii-core#51]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.x
| Operating system | Debian

**Comment by samdark** [comment]
Would you please describe its use case? Also note that there is a standard interface for that in PHP.

**Comment by rustamwin** [comment]
I think it should be for `toJson` methods

**Comment by hiqsol** [comment]
There is already interface for that in PHP:

http://php.net/manual/en/class.jsonserializable.php

**Comment by rustamwin** [comment]
Probably some (contains method `toJson`) classes could be implemented from JsonSerializable
