### ISSUE TITLE
[meta] Remove @author from source

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#54]
Currently some source files have an `@author` PHPDoc.
In an open source project where each file can have a lot of contributors over time I don't see the value of having this.
If we want to know who added the file we can check the git history; also essentially it means nothing since your commits are already strongly connected to you.

**Comment by SamMousa** [comment]
> splitting the repos made the original source hidden in the yii3 repos

This goes for all contributors, not just the original author. But I think adding everyone who contributes in the source doesn't make sense.

> I agree that this is not ideal as it is not clear how much changes are needed by a person to be counted as co-author for a file.

This exactly; just because I created a file doesn't make me more relevant in my opinion. If I create a file and over time it changes significantly is it really relevant that I happened to create it?

While my preference is to remove it because it doesn't do anything, I feel that if we leave it there should be some guidelines / rules at least.

**Comment by samdark** [comment]
I'm for removing it. While it was necessary for early stages where there was no easy `git blame`, in my opinion, it is confusing nowadays as @SamMousa said. Code belongs to Yii community overall and is created and maintained for our common good.

**Comment by samdark** [comment]
@hiqsol, @SilverFire ?

**Comment by cebe** [comment]
okay, agree.

We can automate it via https://github.com/yiisoft/yii2/blob/2.0.15/build/controllers/PhpDocController.php
no need to manually work through the code, these changes are applied at least before every release.

**Comment by machour** [comment]
I'm removing the `@author` tag in log packages, and crediting people in composer.json `authors` field, I think this is the cleanest way to do it.

Agreed? If so, let's change this issue status.

**Comment by samdark** [comment]
Yes.

**Comment by cebe** [comment]
here is a php-cs-fixer config for this, btw: https://github.com/cebe/php-openapi/blob/0e396286714cbe5c872efdcdb027328260be0fe0/.php_cs.dist#L7-L12

**Comment by samdark** [comment]
Mostly done. If there are still files with these, they'll be cleaned up later.
