### ISSUE TITLE
Remove special citizens from `Application`

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#56]
Currently the `Application` class has some special citizens; components that for some unknown reason get their own getter:
```php
/**
     * @return View
     */
    public function getView()
    {
        return $this->get('view');
    }
    /**
     * @return View
     */
    public function getFormatter()
    {
        return $this->get('formatter');
    }
    /**
     * @return Security
     */
    public function getSecurity()
    {
        return $this->get('security');
    }
    /**
     * @return Session
     */
    public function getSession()
    {
        return $this->get('session');
    }
    /**
     * @return User
     */
    public function getUser()
    {
        return $this->get('user');
    }
    /**
     * @deprecated 3.0 use DI instead.
     * @return I18N
     */
    public function getI18n()
    {
        return $this->get('i18n');
    }
    /**
     * Returns the database connection component.
     * @return Connection the database connection.
     */
    public function getDb()
    {
        return $this->get('db');
    }

```

I don't see why this is needed; the exact same syntax is supported by the `Module` base class via `__get()`.

**Comment by samdark** [comment]
Here it is: https://www.xtreamwayz.com/blog/2015-12-14-phpstorm-container-interop-code-completion

**Comment by hiqsol** [comment]
Just don't forget to remove use of these functions spread all around the code.
I think it's better to do this cleaning after fixing tests.

**Comment by SamMousa** [comment]
> I think it's better to do this cleaning after fixing tests.

Agree.

@samdark since we have magic getters for these things we can retrieve them as properties. And properties we can annotate with phpdoc for the default cases.

**Comment by samdark** [comment]
We can annotate both properties and methods.

**Comment by samdark** [comment]
Done.
