### ISSUE TITLE
How about traits Component BaseObject?

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii-core#6]
Sometimes need to use only events&behaviors code from Component, not magic __get __set and __contructor($config) from BaseObject.

```php
class Post implements ComponentEventInterface
{
    use ComponentTrait;

    private $title;

    public function __construct($title)
    {
        $this->title = $title;
    }

    public function changeTitle($title)
    {
        $this->title = $title;
        $this->trigger(TitleChangedEvent::NAME, new TitleChangedEvent());
    }
}
```

https://github.com/yiisoft/core/commit/6d16c1c2d9143f1edde2cc349b2e8b9bd7b87358 +1

**Comment by samdark** [comment]
__contructor($config) was already removed.

**Comment by samdark** [comment]
Decided not to implement BaseObject at all.
