### ISSUE TITLE
implement loadDefaultValues() to yii\base\Model

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/yii-core#64]
now developers can use loadDefaultValues() for ActveRecord, but can`t use it at base Model, think it will be usefull feature to load values that have default value validation rule.
```php
public function loadDefaultValues() {
	foreach ($this->getActiveValidators() as $validator) {
		if ($validator instanceof DefaultValueValidator) {
			$validator->validateAttributes($this, $this->activeAttributes());
		}
	}
}
```

**Comment by rob006** [comment]
`ActiveRecord::loadDefaultValues()` does not use validation rules for loading default values. We should not add the same method with completely different implementation, it will be really confusing. If we implement this it should probably use `get_class_vars()` and load default values of properties defined in class.

**Comment by samdark** [comment]
There's no yii\base\Model  anymore.
