### ISSUE TITLE
DynamicModel unset should not forget about the attribute

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii-core#66]
https://github.com/yiisoft/yii2/blob/cf1bb804831cfb90256328eb302d27c1a4858d99/framework/base/DynamicModel.php#L120

this way the attribute can not be set anymore with which unset would be equal to `undefineAttribute()`.

should be `$this->_attributes[$name] = null;` instead

**Comment by samdark** [comment]
There is going to be no dynamic model in 3.0. Closing.
