### ISSUE TITLE
[2.1] Cleanup ErrorHandler

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#71]
For 2.1 some cleanup can be done in the `ErrorHandler` component.

- [x] Remove `HHVM` code (#14280)
- [x] Check if we can remove `handleFatalError`, since they are now thrown instead.
- [x] (re)Consider using some library like whoops (I know this has been previously considered in #297, but it makes sense to reconsider this from time to time)

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
Re-checked everything and now consider it done: https://forum.yiiframework.com/t/error-handler-is-back/126667
