### ISSUE TITLE
Request/response should be injected in controller, actions and related classes via constructor

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-core#73]
## Current state

Currently we're working with request/response globally via `Yii::$app->request` and `Yii::$app->response`.

## Problem

Encapsulation violated. Request and response aren't meant to be dealt with outside of controller and related classes. Accessing them directly and especially doing that in the guide could be easily interpreted like "accessing request anywhere via Yii::$app->request is OK".

## Suggested syntax

```php
// old
Yii::$app->request->...
Yii::$app->response->...

// new
$this->request->...
$this->response->...
```

**Comment by samdark** [comment]
What else from the app instance is needed in the controller action?

**Comment by bmsrox** [comment]
> Pls. Inject Request class to action params
> 
> ```
> public function actionSave(yii\web\Request $request)
>   {
>       $params  = $request->getBodyParams();
> 
>       //
>   }
> ```

And Inject Response too.

**Comment by samdark** [comment]
It's done now:

```php
<?php
namespace App\Controller;

use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class Hello
{
    private $responseFactory;

    public function __construct(ResponseFactoryInterface $responseFactory)
    {
        $this->responseFactory = $responseFactory;
    }    

    public function say(ServerRequestInterface $request): ResponseInterface
    {
        $message = $request->getAttribute('message', 'Hello!');
        
        $response = $this->responseFactory->createResponse();
        $response->getBody()->write('The message is: ' . $this->encodeHtml($message));
        return $response;
    }
    
    private function encodeHtml(string $string): string
    {
        return htmlspecialchars($string, ENT_QUOTES | ENT_SUBSTITUTE);
    }

}
```

Additional services are be injected if specified in signature.
