### ISSUE TITLE
Accessing application config and environment values

### ISSUE THREAD

**Issue by yii-bot** [yiisoft/yii-core#77]
This issue has originally been reported by @schmunk42 at https://github.com/yiisoft/yii2-app/issues/4.
Moved here by @cebe.

-----

We found it pretty handy to have the ability to get the (**merged**) app-config and environment from a command.

```
    /**
     * Shows application configuration
     * Note that this action shows console configuration.
     *
     * @param null $key configuration section
     */
    public function actionConfig($key = null)
    {
        // get config from global variable (TODO)
        $data = $GLOBALS['config'];
        if ($key) {
            $keys = explode('.', $key);
            if (isset($keys[0])) {
                $data = $GLOBALS['config'][$keys[0]];
            }
            if (isset($keys[1])) {
                $data = $GLOBALS['config'][$keys[0]][$keys[1]];
            }
        }
        $this->stdout(VarDumper::dumpAsString($data));
    }

    /**
     * Shows application environment variables.
     */
    public function actionEnv()
    {
        $env = $_ENV;
        ksort($env);
        $this->stdout(VarDumper::dumpAsString($env));
    }
```

Unfortunately it's a bit hacky in the config part, but this might be an issue for the core.

**Comment by schmunk42** [comment]
@samdark There were a bunch of tickets closed a few hours ago. The ones I've seen without any further comment. 
For this specific one I think it'll be handled via config plugin, but it would be nice to have at least a few words if the others are `fixed`, `wontfix`, `invalid` or whatever...

**Comment by samdark** [comment]
Commented on the tickets closed. It is correct that this one is handled via config plugin.

**Comment by samdark** [comment]
Sorry for not commenting. Was too deep into code :(
