### ISSUE TITLE
Add optional context to `resolveCallableDependencies`

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-core#78]
Now that modules have tree traversal we should add context to `resolveCallableDependencies`.

### What steps will reproduce the problem?

Application has `User` component.
Module A has `User` component.

Somewhere in Module A try to use `resolveCallableDependencies` on something that requires a `User` component.

### What is the DESIRED result?

I'd love to get my modules' `User` component.

### What do you get instead?
The applications' `User` component.

### Additional info

Basically the way `\Yii::$app` is used in the container is as a preferred `ServiceLocator`. Instead we could support passing in any `ServiceLocator` as a context.

Current signature:

```php
public function resolveCallableDependencies(callable $callback, $params = [])
```
Proposed signature:

```php
public function resolveCallableDependencies(callable $callback, $params = [], ServiceLocator $context = null)
```

Temporary backwards compatible implementation:

```php
public function resolveCallableDependencies(callable $callback, $params = [], ServiceLocator $context = null) {
if (!isset($context)) {
    $context = \Yii::$app;
}
```
At some point we should then remove the default and always require explicit context (thus removing the access to the global).

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Closing since implementation is too different now.
