### ISSUE TITLE
Fix Git comments style

### ISSUE THREAD

**Issue by vstokarev** [yiisoft/yii-core#8]
Couple proposals for framework developers. It would be nice if you could follow best practices when writing Git comments: https://chris.beams.io/posts/git-commit/
In Russian: https://habr.com/post/416887/

Also, consider using this format for the project change log: https://keepachangelog.com/en/1.0.0/

Thanks.

**Comment by githubjeka** [comment]
Thanks for sharing.
This makes you take seriously every little thing.

**Comment by vstokarev** [comment]
Yeah, I personally like current Yii change log style, it's good enough and is quite readable. The reason I proposed it is that it _may_ become as popular as semver in future (or may not), so I wanted to know your opinion on this.

**Comment by samdark** [comment]
There's no style defined for it.

**Comment by machour** [comment]
I have a personal preference for [angular commit conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit). When used strictly, changelog & even releases can be automated using a multitude of available tools, like:
* https://github.com/conventional-changelog/conventional-changelog
* https://github.com/semantic-release/semantic-release

**Comment by samdark** [comment]
https://github.com/yiisoft/docs/blob/master/006-git-commit-messages.md
