### ISSUE TITLE
Pass result of run() to afterRun() in yii\base\Action?

### ISSUE THREAD

**Issue by egml** [yiisoft/yii-core#86]
It seems reasonable when you inherit some base action class and want to further process the result or change behavior of `afterRun()` depending on the result. But are there any caveats of passing whole result every action run? Or any other methods? Right now inheriting `yii\base\Action` and duplicating `runWithParams()` doesn't seem ok.
Some distantly related issue: https://github.com/yiisoft/yii2/issues/2549.

**Comment by samdark** [comment]
The issue doesn't apply to new code anymore.
