### ISSUE TITLE
No way of overriding controller actions 

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii-core#93]
Currently I see no way of extending controller with its actions because the render function at the end returns the HTML content instead of a View object which can be manipulated before render to HTML. Let me just give you an example:
We have a BaseController which renders a gridview with a $dataProvider param. Later I want to extend the BaseController's index action and to add aditional parameters or modify the existing ones so I override the actionIndex method and when I use parent::actionIndex() the return value is string. So there is no way to override it(without some kind of workaround this limitation). 
There is a slight inconsistency here because for example the RestController's actions return arrays or object and thus can be easily overridden,  There results are later rendered to string which is returned. 
IMO the controllers should return View objects(not rendered) which can be modified and then later rendered in runActionFunction for example. What do you think ?

**Comment by samdark** [comment]
It's all different now.
