### ISSUE TITLE
Separate the part of Composer Autoload Psr from `aliases`

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-core#98]
According to the definition of the alias for the document, the alias should only be used to handle `Paths` and `URLs`.
The value of the `alias` can only be a `string`
See: https://www.yiiframework.com/doc/guide/2.0/en/concept-aliases

And Composer Autoload Psr map can be an array
After separation, we will be able to implement more useful features and comply with `Psr`
E.g: Supports multiple directories with `namespace`, which can be used for migration and base template combination. Of course there are many
See: https://github.com/yiisoft/db/issues/29#issuecomment-440586266

I think  can add an `PsrAliases.php` file. 
You can use it like the alias component.
The property is read-only, and the content inside is completely generated according to composer

The original alias is configured by `config`.
```
    'aliases' => [
        '__class'   => yii\base\Aliases::class,
        '@root'     => YII_ROOT,
        '@vendor'   => '@root/vendor',
        '@public'   => '@root/public',
        '@runtime'  => '@root/runtime',
        '@bower'    => '@vendor/bower-asset',
        '@npm'      => '@vendor/npm-asset',
        '@yii'      => '@vendor/yiisoft/yii-core/src',
        '@yiisoft'  => '@vendor/yiisoft',
    ],
```
Because aliases are basically only used for paths, it will be more intuitive.
```php
public $sourcePath = '@yiisoft/yii-jquery/src/assets';
or
public $sourcePath = '@vendor/yiisoft/yii-jquery/src/assets';
```
Users can configure custom aliases based on their own needs.
I am working on the relevant changes, and if I allow me to perfect it. And submit `PR`.
Is there a good suggestion if you name it?

**Comment by kids-return** [comment]
Forgive me for not understanding, can you tell me your opinion?  🥺
or
👍   👎

**Comment by schmunk42** [comment]
@kids-return There's no simply yes or no from my side. I was just pointing out a useful feature at the moment, which should be kept, if there's no better alternative. It looks like your proposal touches that part.

**Comment by kids-return** [comment]
old
```
yii migrate/up --migration-path=@leonsw/wallet/migrations,@leonsw/user/migrations,@leonsw/post/migrations,@leonsw/tag/migrations
```
now
```
yii migrate/up --migration-path=@leonsw/migrations
```
use $psrAliases->get('@leonsw/migrations')
Can get multiple directories
I think this is the right thing.

> Aliases are used to represent file paths or URLs so that you don't have to hard-code absolute paths or URLs in your project. An alias must start with the @ character to be differentiated from normal file paths and URLs. Alias defined without leading @ will be prefixed with @ character.

I suggest you look at the above again.

**Comment by kids-return** [comment]
i18n
```php
$psrAliases->get('@leonsw/messages')
```

**Comment by samdark** [comment]
Done.
